<a href="https://colab.research.google.com/github/MeeraReji/AFLL-CFG-of-ruby-lang/blob/main/ANN(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.15.0'

In [3]:
dataset=pd.read_csv('/content/Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [4]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
#feature Scaling:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
ann=tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics=['accuracy'])

In [16]:
ann.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.5272 - accuracy: 0.7928
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4520 - accuracy: 0.8024
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4326 - accuracy: 0.8133
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4223 - accuracy: 0.8194
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4159 - accuracy: 0.8242
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4113 - accuracy: 0.8285
Epoch 7/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4065 - accuracy: 0.8313
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8353
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3940 - accuracy: 0.8369
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3871 - accura

In [20]:
 print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 30ms/step
[[False]]
